import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { stableApi } from "../../api/stables";
import Breadcrumb from "../shared/Breadcrumb";
import SubTabs from "../shared/SubTabs";
import { useModuleTab } from "../shared/useModuleTab";

const text = {
  ar: { title:"إسطبلات الخيل", overview:"نظرة عامة", stables:"الإسطبلات", stalls:"البوكسات", horses:"الخيول", contracts:"عقود الإيواء", care:"الرعاية", add:"إضافة", save:"حفظ التعديلات", cancel:"إلغاء", edit:"تعديل", del:"حذف", loading:"جارٍ التحميل...", empty:"لا توجد سجلات", name:"الاسم", code:"الكود", location:"الموقع", manager:"المسؤول", phone:"الهاتف", capacity:"السعة", notes:"ملاحظات", stable:"الإسطبل", number:"رقم البوكس", type:"النوع", rate:"السعر اليومي", status:"الحالة", horse:"الخيل", reg:"رقم التسجيل", chip:"رقم الشريحة", breed:"السلالة", color:"اللون", sex:"الجنس", birth:"تاريخ الميلاد", owner:"المالك", ownerPhone:"هاتف المالك", stall:"البوكس", start:"البداية", end:"النهاية", monthly:"الرسوم الشهرية", deposit:"التأمين", date:"التاريخ", provider:"مقدم الخدمة", description:"الوصف", cost:"التكلفة", next:"الموعد القادم", activeHorses:"الخيول النشطة", availableStalls:"البوكسات المتاحة", activeContracts:"العقود النشطة", upcoming:"مواعيد الرعاية خلال 30 يومًا", confirm:"هل تريد حذف هذا السجل؟", required:"أكمل الحقول المطلوبة" },
  en: { title:"Horse Stables", overview:"Overview", stables:"Stables", stalls:"Stalls", horses:"Horses", contracts:"Boarding", care:"Care records", add:"Add", save:"Save changes", cancel:"Cancel", edit:"Edit", del:"Delete", loading:"Loading...", empty:"No records", name:"Name", code:"Code", location:"Location", manager:"Manager", phone:"Phone", capacity:"Capacity", notes:"Notes", stable:"Stable", number:"Stall no.", type:"Type", rate:"Daily rate", status:"Status", horse:"Horse", reg:"Registration no.", chip:"Microchip no.", breed:"Breed", color:"Color", sex:"Sex", birth:"Birth date", owner:"Owner", ownerPhone:"Owner phone", stall:"Stall", start:"Start", end:"End", monthly:"Monthly fee", deposit:"Deposit", date:"Date", provider:"Provider", description:"Description", cost:"Cost", next:"Next due", activeHorses:"Active horses", availableStalls:"Available stalls", activeContracts:"Active contracts", upcoming:"Care due in 30 days", confirm:"Delete this record?", required:"Complete the required fields" },
};
export const STABLE_TABS = ["overview","stables","stalls","horses","contracts","care"].map(id => ({ id, labelKey:`stables.${id}` }));
const empty = {
  stables:{name:"",code:"",location:"",managerName:"",phone:"",capacity:0,notes:""},
  stalls:{stableId:"",number:"",type:"",dailyRate:"",status:"available",notes:""},
  horses:{name:"",registrationNo:"",microchipNo:"",breed:"",color:"",sex:"mare",birthDate:"",ownerName:"",ownerPhone:"",stableId:"",stallId:"",status:"active",notes:""},
  contracts:{horseId:"",stableId:"",stallId:"",startDate:new Date().toISOString().slice(0,10),endDate:"",monthlyFee:"",depositAmount:"",status:"active",notes:""},
  care:{horseId:"",type:"veterinary",performedAt:new Date().toISOString().slice(0,10),provider:"",description:"",cost:"",nextDueDate:"",notes:""},
};
const clean = (obj) => Object.fromEntries(Object.entries(obj).map(([k,v]) => [k, v === "" ? null : v]));
const fmtDate = (v) => v ? new Date(v).toLocaleDateString() : "—";

function Editor({ kind, value, setValue, L, stables, stalls, horses }) {
  const f = (key,label,type="text",required=false) => <label>{label}{required?" *":""}<input type={type} value={value[key] ?? ""} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>;
  const select = (key,label,options) => <label>{label}<select value={value[key] ?? ""} onChange={e=>setValue({...value,[key]:e.target.value})}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
  if(kind==="stables") return <>{f("name",L.name,"text",true)}{f("code",L.code)}{f("location",L.location)}{f("managerName",L.manager)}{f("phone",L.phone)}{f("capacity",L.capacity,"number")}{f("notes",L.notes)}</>;
  if(kind==="stalls") return <>{select("stableId",L.stable,[["","—"],...stables.map(x=>[x.id,x.name])])}{f("number",L.number,"text",true)}{f("type",L.type)}{f("dailyRate",L.rate,"number")}{select("status",L.status,[["available","Available"],["occupied","Occupied"],["maintenance","Maintenance"],["inactive","Inactive"]])}{f("notes",L.notes)}</>;
  if(kind==="horses") return <>{f("name",L.name,"text",true)}{f("registrationNo",L.reg)}{f("microchipNo",L.chip)}{f("breed",L.breed)}{f("color",L.color)}{select("sex",L.sex,[["stallion","Stallion"],["mare","Mare"],["gelding","Gelding"]])}{f("birthDate",L.birth,"date")}{f("ownerName",L.owner)}{f("ownerPhone",L.ownerPhone)}{select("stableId",L.stable,[["","—"],...stables.map(x=>[x.id,x.name])])}{select("stallId",L.stall,[["","—"],...stalls.filter(x=>!value.stableId||x.stableId===value.stableId).map(x=>[x.id,x.number])])}{select("status",L.status,[["active","Active"],["training","Training"],["resting","Resting"],["medical_hold","Medical hold"],["sold","Sold"],["deceased","Deceased"]])}{f("notes",L.notes)}</>;
  if(kind==="contracts") return <>{select("horseId",L.horse,[["","—"],...horses.map(x=>[x.id,x.name])])}{select("stableId",L.stable,[["","—"],...stables.map(x=>[x.id,x.name])])}{select("stallId",L.stall,[["","—"],...stalls.filter(x=>!value.stableId||x.stableId===value.stableId).map(x=>[x.id,x.number])])}{f("startDate",L.start,"date",true)}{f("endDate",L.end,"date")}{f("monthlyFee",L.monthly,"number",true)}{f("depositAmount",L.deposit,"number")}{select("status",L.status,[["active","Active"],["completed","Completed"],["cancelled","Cancelled"]])}{f("notes",L.notes)}</>;
  return <>{select("horseId",L.horse,[["","—"],...horses.map(x=>[x.id,x.name])])}{select("type",L.type,[["veterinary","Veterinary"],["vaccination","Vaccination"],["farrier","Farrier"],["feeding","Feeding"],["training","Training"],["grooming","Grooming"],["medication","Medication"],["other","Other"]])}{f("performedAt",L.date,"date",true)}{f("provider",L.provider)}{f("description",L.description,"text",true)}{f("cost",L.cost,"number")}{f("nextDueDate",L.next,"date")}{f("notes",L.notes)}</>;
}

export default function StablesModule({ companyId }) {
  const { i18n } = useTranslation(); const L=text[i18n.language?.startsWith("ar")?"ar":"en"];
  const tabs=useMemo(()=>STABLE_TABS.map(x=>({...x,label:L[x.id]})),[L]); const [tab]=useModuleTab("/stables",tabs);
  const [data,setData]=useState({overview:null,stables:[],stalls:[],horses:[],contracts:[],care:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty[tab]||{});
  const load=useCallback(async()=>{if(!companyId)return;setLoading(true);setError("");try{const [overview,stables,stalls,horses,contracts,care]=await Promise.all([stableApi.overview(companyId),stableApi.listStables(companyId),stableApi.listStalls(companyId),stableApi.listHorses(companyId),stableApi.listContracts(companyId),stableApi.listCare(companyId)]);setData({overview,stables,stalls,horses,contracts,care});}catch(e){setError(e.message)}finally{setLoading(false)}},[companyId]);
  useEffect(()=>{load()},[load]); useEffect(()=>{setEditing(null);setForm({...empty[tab]})},[tab]);
  if(!companyId)return <p className="empty">{L.required}</p>;
  const save=async()=>{try{const payload={...clean(form),companyId}; const singular={stables:"Stable",stalls:"Stall",horses:"Horse",contracts:"Contract",care:"Care"}[tab]; if(editing) await stableApi[`update${singular}`](editing,payload); else await stableApi[`create${singular}`](payload); setEditing(null);setForm({...empty[tab]});await load();}catch(e){setError(e.message)}};
  const remove=async(id)=>{if(!window.confirm(L.confirm))return;try{const singular={stables:"Stable",stalls:"Stall",horses:"Horse",contracts:"Contract",care:"Care"}[tab];await stableApi[`delete${singular}`](id);await load()}catch(e){setError(e.message)}};
  const edit=(r)=>{setEditing(r.id);setForm(Object.fromEntries(Object.keys(empty[tab]).map(k=>[k,(k.endsWith("Date")||k==="performedAt"||k==="startDate"||k==="endDate")&&r[k]?new Date(r[k]).toISOString().slice(0,10):(r[k]??"")])))};
  const rows=data[tab]||[];
  return <div><div className="section-title"><Breadcrumb parts={[L.title]}/><h2>{L.title}</h2></div><SubTabs tabs={tabs} active={tab} basePath="/stables"/>{error&&<p className="balance-bad">{error}</p>}
    {tab==="overview"&&data.overview&&<><div className="kpi-grid"><div className="kpi-card"><strong>{data.overview.stables}</strong><span>{L.stables}</span></div><div className="kpi-card"><strong>{data.overview.horses}</strong><span>{L.activeHorses}</span></div><div className="kpi-card"><strong>{data.overview.availableStalls}</strong><span>{L.availableStalls}</span></div><div className="kpi-card"><strong>{data.overview.activeContracts}</strong><span>{L.activeContracts}</span></div></div><div className="panel"><h3>{L.upcoming}</h3>{data.overview.upcomingCare.map(x=><p key={x.id}>{x.horse.name} — {x.description} — {fmtDate(x.nextDueDate)}</p>)}{!data.overview.upcomingCare.length&&<p className="empty">{L.empty}</p>}</div></>}
    {tab!=="overview"&&<><div className="panel form-panel"><div className="form-grid"><Editor kind={tab} value={form} setValue={setForm} L={L} {...data}/></div><div className="form-btn-group">{editing&&<button className="btn-ghost" onClick={()=>{setEditing(null);setForm({...empty[tab]})}}>{L.cancel}</button>}<button className="btn-primary" onClick={save}>{editing?L.save:L.add}</button></div></div>{loading?<p className="empty">{L.loading}</p>:<div className="panel"><table className="ledger-table"><thead><tr><th>{tab==="stalls"?L.number:tab==="care"?L.description:L.name}</th><th>{L.stable}</th><th>{L.status}</th><th>{L.notes}</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name||r.number||r.description}</td><td>{r.stable?.name||r.horse?.name||"—"}</td><td>{r.status||r.type||"—"}</td><td>{r.notes||"—"}</td><td className="row-actions"><button className="btn-ghost" onClick={()=>edit(r)}>{L.edit}</button><button className="btn-ghost" onClick={()=>remove(r.id)}>{L.del}</button></td></tr>)}{!rows.length&&<tr><td colSpan="5" className="empty">{L.empty}</td></tr>}</tbody></table></div>}</>}
  </div>;
}

