import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { stableApi } from "../../api/stables";
import Breadcrumb from "../shared/Breadcrumb";
import SubTabs from "../shared/SubTabs";
import { useModuleTab } from "../shared/useModuleTab";
import { NavIcon } from "../../legacy/navIcons";

const extraText = {
  ar:{trainers:"المدربون",lessonTypes:"أنواع الحصص",lessons:"الحصص",competitions:"المسابقات",services:"دليل الخدمات",billing:"إنشاء فاتورة إعاشة",commissions:"عمولات المدربين",specialties:"التخصصات",bio:"نبذة",level:"المستوى",duration:"المدة بالدقائق",format:"نظام الحصة",capacity:"عدد المتدربين",price:"السعر",student:"اسم المتدرب",participants:"عدد المشاركين",discipline:"نوع المنافسة",rider:"الفارس",result:"النتيجة",category:"التصنيف",nameAr:"اسم الخدمة بالعربية",nameEn:"اسم الخدمة بالإنجليزية",unit:"وحدة التسعير",commissionPct:"نسبة العمولة %",monthlyServices:"الخدمات الشهرية الثابتة",ownerEmail:"بريد المالك",createdDraft:"تم إنشاء فاتورة الإعاشة كمسودة للمراجعة",lessonInvoice:"إنشاء فاتورة الحصة",invoiceCreated:"تم إنشاء فاتورة الحصة كمسودة"},
  en:{trainers:"Trainers",lessonTypes:"Lesson types",lessons:"Lessons",competitions:"Competitions",services:"Service catalog",billing:"Create boarding invoice",commissions:"Trainer commissions",specialties:"Specialties",bio:"Bio",level:"Level",duration:"Duration (minutes)",format:"Lesson format",capacity:"Capacity",price:"Price",student:"Student",participants:"Participants",discipline:"Discipline",rider:"Rider",result:"Result",category:"Category",nameAr:"Arabic service name",nameEn:"English service name",unit:"Pricing unit",commissionPct:"Commission %",monthlyServices:"Fixed monthly services",ownerEmail:"Owner email",createdDraft:"Boarding invoice created as a draft for review",lessonInvoice:"Create lesson invoice",invoiceCreated:"Lesson invoice created as draft"}
};
const text = {
  ar: { title:"إسطبلات الخيل", overview:"نظرة عامة", stables:"الإسطبلات", stalls:"البوكسات", horses:"الخيول", contracts:"عقود الإيواء", care:"الرعاية", add:"إضافة", save:"حفظ التعديلات", cancel:"إلغاء", edit:"تعديل", del:"حذف", print:"طباعة العقد", send:"إرسال للمالك", sent:"تم إرسال العقد", loading:"جارٍ التحميل...", empty:"لا توجد سجلات", name:"الاسم", code:"الكود", location:"الموقع", manager:"المسؤول", phone:"الهاتف", email:"البريد الإلكتروني", nationality:"الجنسية", nationalId:"رقم الهوية", issuePlace:"مكان إصدار الهوية", city:"المدينة", district:"الحي", street:"الشارع", building:"رقم المبنى", postal:"الرمز البريدي", contractNo:"رقم العقد", capacity:"السعة", notes:"ملاحظات", stable:"الإسطبل", number:"رقم البوكس", type:"النوع", rate:"السعر اليومي", status:"الحالة", horse:"الخيل", reg:"رقم التسجيل", chip:"رقم الشريحة", breed:"السلالة", color:"اللون", sex:"الجنس", birth:"تاريخ الميلاد", owner:"المالك", ownerPhone:"هاتف المالك", stall:"البوكس", start:"البداية", end:"النهاية", monthly:"الرسوم الشهرية", deposit:"التأمين", date:"التاريخ", provider:"مقدم الخدمة", description:"الوصف", cost:"التكلفة", next:"الموعد القادم", activeHorses:"الخيول النشطة", availableStalls:"البوكسات المتاحة", activeContracts:"العقود النشطة", upcoming:"مواعيد الرعاية خلال 30 يومًا", confirm:"هل تريد حذف هذا السجل؟", required:"أكمل الحقول المطلوبة" },
  en: { title:"Horse Stables", overview:"Overview", stables:"Stables", stalls:"Stalls", horses:"Horses", contracts:"Boarding", care:"Care records", add:"Add", save:"Save changes", cancel:"Cancel", edit:"Edit", del:"Delete", print:"Print contract", send:"Email owner", sent:"Contract sent", loading:"Loading...", empty:"No records", name:"Name", code:"Code", location:"Location", manager:"Manager", phone:"Phone", email:"Email", nationality:"Nationality", nationalId:"ID number", issuePlace:"ID issue place", city:"City", district:"District", street:"Street", building:"Building no.", postal:"Postal code", contractNo:"Contract no.", capacity:"Capacity", notes:"Notes", stable:"Stable", number:"Stall no.", type:"Type", rate:"Daily rate", status:"Status", horse:"Horse", reg:"Registration no.", chip:"Microchip no.", breed:"Breed", color:"Color", sex:"Sex", birth:"Birth date", owner:"Owner", ownerPhone:"Owner phone", stall:"Stall", start:"Start", end:"End", monthly:"Monthly fee", deposit:"Deposit", date:"Date", provider:"Provider", description:"Description", cost:"Cost", next:"Next due", activeHorses:"Active horses", availableStalls:"Available stalls", activeContracts:"Active contracts", upcoming:"Care due in 30 days", confirm:"Delete this record?", required:"Complete the required fields" },
};
export const STABLE_TABS = ["overview","stables","stalls","horses","contracts","care","services","trainers","lessonTypes","lessons","competitions","billing","commissions"].map(id => ({ id, labelKey:`stables.${id}` }));
const empty = {
  stables:{name:"",code:"",location:"",managerName:"",phone:"",capacity:0,notes:""},
  stalls:{stableId:"",number:"",type:"",dailyRate:"",status:"available",notes:""},
  horses:{name:"",registrationNo:"",microchipNo:"",breed:"",color:"",sex:"mare",birthDate:"",ownerName:"",ownerPhone:"",ownerEmail:"",ownerNationalId:"",stableId:"",stallId:"",status:"active",monthlyServices:[],notes:""},
  contracts:{contractNumber:"",horseId:"",stableId:"",stallId:"",startDate:new Date().toISOString().slice(0,10),endDate:"",monthlyFee:"",depositAmount:"",ownerName:"",ownerNationality:"",ownerNationalId:"",ownerIdIssuePlace:"",ownerPhone:"",ownerEmail:"",ownerCity:"",ownerDistrict:"",ownerStreet:"",ownerBuildingNo:"",ownerPostalCode:"",status:"active",notes:""},
  care:{horseId:"",type:"veterinary",performedAt:new Date().toISOString().slice(0,10),provider:"",description:"",cost:"",nextDueDate:"",notes:""},
  trainers:{name:"",phone:"",email:"",specialties:"",bio:"",commissionPct:5,isActive:true},
  lessonTypes:{name:"",level:"beginner",durationMinutes:45,format:"individual",capacity:1,price:"",trainerId:"",description:"",isActive:true},
  lessons:{lessonTypeId:"",trainerId:"",horseId:"",studentName:"",studentPhone:"",studentEmail:"",scheduledAt:new Date().toISOString().slice(0,16),participants:1,price:"",status:"scheduled",notes:""},
  competitions:{name:"",discipline:"show_jumping",level:"",location:"",startDate:new Date().toISOString().slice(0,10),endDate:"",registrationDeadline:"",entryFee:"",horseId:"",trainerId:"",riderName:"",status:"planned",result:"",notes:""},
  services:{code:"",category:"veterinary",nameAr:"",nameEn:"",price:"",priceIncludesVat:true,unit:"service",isActive:true},
};
const clean = (obj) => Object.fromEntries(Object.entries(obj).map(([k,v]) => [k, v === "" ? null : v]));
const fmtDate = (v) => v ? new Date(v).toLocaleDateString() : "—";

function Editor({ kind, value, setValue, L, stables, stalls, horses, trainers, lessonTypes, services }) {
  const f = (key,label,type="text",required=false) => <label>{label}{required?" *":""}<input type={type} value={value[key] ?? ""} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>;
  const select = (key,label,options) => <label>{label}<select value={value[key] ?? ""} onChange={e=>setValue({...value,[key]:e.target.value})}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
  if(kind==="stables") return <>{f("name",L.name,"text",true)}{f("code",L.code)}{f("location",L.location)}{f("managerName",L.manager)}{f("phone",L.phone)}{f("capacity",L.capacity,"number")}{f("notes",L.notes)}</>;
  if(kind==="stalls") return <>{select("stableId",L.stable,[["","—"],...stables.map(x=>[x.id,x.name])])}{f("number",L.number,"text",true)}{f("type",L.type)}{f("dailyRate",L.rate,"number")}{select("status",L.status,[["available","Available"],["occupied","Occupied"],["maintenance","Maintenance"],["inactive","Inactive"]])}{f("notes",L.notes)}</>;
  if(kind==="horses") { const selected=value.monthlyServices||[]; const toggle=(service)=>{const found=selected.find(x=>x.serviceId===service.id);setValue({...value,monthlyServices:found?selected.filter(x=>x.serviceId!==service.id):[...selected,{serviceId:service.id,quantity:1,unitPrice:service.price||"",trainerId:""}]})}; return <>{f("name",L.name,"text",true)}{f("registrationNo",L.reg)}{f("microchipNo",L.chip)}{f("breed",L.breed)}{f("color",L.color)}{select("sex",L.sex,[["stallion","Stallion"],["mare","Mare"],["gelding","Gelding"]])}{f("birthDate",L.birth,"date")}{f("ownerName",L.owner,"text",true)}{f("ownerPhone",L.ownerPhone)}{f("ownerEmail",L.ownerEmail,"email")}{f("ownerNationalId",L.nationalId)}{select("stableId",L.stable,[["","—"],...stables.map(x=>[x.id,x.name])])}{select("stallId",L.stall,[["","—"],...stalls.filter(x=>!value.stableId||x.stableId===value.stableId).map(x=>[x.id,x.number])])}{select("status",L.status,[["active","Active"],["training","Training"],["resting","Resting"],["medical_hold","Medical hold"],["sold","Sold"],["deceased","Deceased"]])}<fieldset className="stable-services-fieldset"><legend>{L.monthlyServices}</legend>{services.filter(s=>s.isActive).map(service=>{const row=selected.find(x=>x.serviceId===service.id);return <div className="stable-service-choice" key={service.id}><label><input type="checkbox" checked={Boolean(row)} onChange={()=>toggle(service)}/>{service.nameAr} — {Number(service.price||0).toFixed(2)}</label>{row&&<><input type="number" min="0" step="0.01" value={row.unitPrice??""} onChange={e=>setValue({...value,monthlyServices:selected.map(x=>x.serviceId===service.id?{...x,unitPrice:e.target.value}:x)})}/>{["training","competition"].includes(service.category)&&<select value={row.trainerId||""} onChange={e=>setValue({...value,monthlyServices:selected.map(x=>x.serviceId===service.id?{...x,trainerId:e.target.value}:x)})}><option value="">— المدرب —</option>{trainers.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}</>}</div>})}</fieldset>{f("notes",L.notes)}</> }
  if(kind==="contracts") return <>{f("contractNumber",L.contractNo)}{select("horseId",L.horse,[["","—"],...horses.map(x=>[x.id,x.name])])}{select("stableId",L.stable,[["","—"],...stables.map(x=>[x.id,x.name])])}{select("stallId",L.stall,[["","—"],...stalls.filter(x=>!value.stableId||x.stableId===value.stableId).map(x=>[x.id,x.number])])}{f("startDate",L.start,"date",true)}{f("endDate",L.end,"date")}{f("monthlyFee",L.monthly,"number",true)}{f("depositAmount",L.deposit,"number")}{f("ownerName",L.owner,"text",true)}{f("ownerNationality",L.nationality)}{f("ownerNationalId",L.nationalId)}{f("ownerIdIssuePlace",L.issuePlace)}{f("ownerPhone",L.ownerPhone)}{f("ownerEmail",L.email,"email")}{f("ownerCity",L.city)}{f("ownerDistrict",L.district)}{f("ownerStreet",L.street)}{f("ownerBuildingNo",L.building)}{f("ownerPostalCode",L.postal)}{select("status",L.status,[["active","Active"],["completed","Completed"],["cancelled","Cancelled"]])}{f("notes",L.notes)}</>;
  if(kind==="trainers")return <>{f("name",L.name,"text",true)}{f("phone",L.phone)}{f("email",L.email,"email")}{f("specialties",L.specialties)}{f("commissionPct",L.commissionPct,"number",true)}{f("bio",L.bio)}</>;
  if(kind==="lessonTypes")return <>{f("name",L.name,"text",true)}{select("level",L.level,[["beginner","Beginner"],["intermediate","Intermediate"],["advanced","Advanced"],["competition","Competition"]])}{f("durationMinutes",L.duration,"number",true)}{select("format",L.format,[["individual","Individual"],["pair","Pair"],["group","Group"]])}{f("capacity",L.capacity,"number",true)}{f("price",L.price,"number",true)}{select("trainerId",L.trainers,[["","—"],...trainers.map(x=>[x.id,x.name])])}{f("description",L.description)}</>;
  if(kind==="lessons")return <>{select("lessonTypeId",L.lessonTypes,[["","—"],...lessonTypes.map(x=>[x.id,x.name])])}{select("trainerId",L.trainers,[["","—"],...trainers.map(x=>[x.id,x.name])])}{select("horseId",L.horse,[["","—"],...horses.map(x=>[x.id,x.name])])}{f("studentName",L.student,"text",true)}{f("studentPhone",L.phone)}{f("studentEmail",L.email,"email")}{f("scheduledAt",L.date,"datetime-local",true)}{f("participants",L.participants,"number")}{f("price",L.price,"number",true)}{select("status",L.status,[["scheduled","Scheduled"],["completed","Completed"],["cancelled","Cancelled"],["no_show","No show"]])}{f("notes",L.notes)}</>;
  if(kind==="competitions")return <>{f("name",L.name,"text",true)}{f("discipline",L.discipline,"text",true)}{f("level",L.level)}{f("location",L.location,"text",true)}{f("startDate",L.start,"date",true)}{f("endDate",L.end,"date")}{f("registrationDeadline",L.date,"date")}{f("entryFee",L.price,"number")}{select("horseId",L.horse,[["","—"],...horses.map(x=>[x.id,x.name])])}{select("trainerId",L.trainers,[["","—"],...trainers.map(x=>[x.id,x.name])])}{f("riderName",L.rider)}{select("status",L.status,[["planned","Planned"],["registered","Registered"],["completed","Completed"],["cancelled","Cancelled"]])}{f("result",L.result)}{f("notes",L.notes)}</>;
  if(kind==="services")return <>{f("code",L.code)}{select("category",L.category,[["livery","Livery"],["nursing","Nursing"],["veterinary","Veterinary"],["farrier","Farrier"],["breeding","Breeding"],["grooming","Grooming"],["dental","Dental"],["training","Training"],["competition","Competition"],["supplies","Supplies"],["optional","Optional"]])}{f("nameAr",L.nameAr,"text",true)}{f("nameEn",L.nameEn)}{f("price",L.price,"number")}{f("unit",L.unit,"text",true)}</>;
  return <>{select("horseId",L.horse,[["","—"],...horses.map(x=>[x.id,x.name])])}{select("type",L.type,[["veterinary","Veterinary"],["vaccination","Vaccination"],["farrier","Farrier"],["feeding","Feeding"],["training","Training"],["grooming","Grooming"],["medication","Medication"],["other","Other"]])}{f("performedAt",L.date,"date",true)}{f("provider",L.provider)}{f("description",L.description,"text",true)}{f("cost",L.cost,"number")}{f("nextDueDate",L.next,"date")}{f("notes",L.notes)}</>;
}

function BoardingBillingPanel({ companyId, owners, trainers, L, onCreated }) {
  const [customerId,setCustomerId]=useState(""); const [billingMonth,setBillingMonth]=useState(new Date().toISOString().slice(0,7)); const [trainerSelections,setTrainerSelections]=useState({}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const owner=owners.find(x=>x.id===customerId); const assignments=(owner?.horses||[]).flatMap(h=>h.monthlyServices.map(a=>({horse:h,...a})));
  const create=async()=>{if(!customerId)return;setBusy(true);setMessage("");try{const result=await stableApi.createBoardingInvoice({companyId,customerId,billingMonth,trainerSelections});setMessage(`${L.createdDraft}: ${result.salesInvoice.invoiceNumber}`);await onCreated()}catch(e){setMessage(e.message)}finally{setBusy(false)}};
  return <div className="panel boarding-billing-panel"><div className="form-grid"><label>{L.owner} *<select value={customerId} onChange={e=>{setCustomerId(e.target.value);setTrainerSelections({})}}><option value="">—</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>{L.monthly}<input type="month" value={billingMonth} onChange={e=>setBillingMonth(e.target.value)}/></label></div>{owner&&<div className="boarding-preview">{owner.horses.map(h=><section key={h.id}><h3>{h.name}</h3>{h.monthlyServices.length?h.monthlyServices.map(a=><div className="boarding-service-row" key={a.id}><span>{a.service.nameAr}</span><strong>{Number(a.unitPrice??a.service.price??0).toFixed(2)}</strong>{["training","competition"].includes(a.service.category)&&<select value={trainerSelections[a.id]??a.trainerId??""} onChange={e=>setTrainerSelections({...trainerSelections,[a.id]:e.target.value})}><option value="">— المدرب —</option>{trainers.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.name} ({Number(t.commissionPct)}%)</option>)}</select>}</div>):<p className="empty">{L.empty}</p>}</section>)}</div>}{message&&<p className="balance-good">{message}</p>}<div className="form-btn-group"><button className="btn-primary" disabled={!customerId||!assignments.length||busy} onClick={create}><NavIcon name="billing"/> {busy?L.loading:L.billing}</button></div></div>;
}

function CommissionReportPanel({ companyId, L }) {
  const now=new Date(); const [from,setFrom]=useState(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`); const [to,setTo]=useState(now.toISOString().slice(0,10)); const [report,setReport]=useState({rows:[],totals:{netRevenue:0,commission:0}}); const [error,setError]=useState("");
  const load=async()=>{try{setError("");setReport(await stableApi.trainerCommissionReport(companyId,from,to))}catch(e){setError(e.message)}}; useEffect(()=>{load()},[companyId]);
  return <div className="panel commission-report"><div className="form-grid"><label>{L.start}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{L.end}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="form-btn-group no-print"><button className="btn-ghost" onClick={load}>عرض التقرير</button><button className="btn-primary" onClick={()=>window.print()}><NavIcon name="print"/> {L.print}</button></div>{error&&<p className="balance-bad">{error}</p>}<div className="kpi-grid"><div className="kpi-card"><strong>{Number(report.totals.horseTrainingCommission||0).toFixed(2)}</strong><span>عمولات تدريب الخيل</span></div><div className="kpi-card"><strong>{Number(report.totals.lessonCommission||0).toFixed(2)}</strong><span>عمولات الحصص</span></div></div><table className="ledger-table"><thead><tr><th>نوع العمولة</th><th>{L.trainers}</th><th>{L.horse}</th><th>{L.date}</th><th>صافي إيراد التدريب</th><th>{L.commissionPct}</th><th>العمولة المستحقة</th><th>{L.status}</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.id}><td>{r.sourceType==="riding_lesson"?"حصة متدرب":"تدريب خيل"}</td><td>{r.trainer.name}</td><td>{r.horse?.name||"—"}</td><td>{fmtDate(r.periodStart)} — {fmtDate(r.periodEnd)}</td><td>{Number(r.netTrainingRevenue).toFixed(2)}</td><td>{Number(r.commissionPct)}%</td><td>{Number(r.commissionAmount).toFixed(2)}</td><td>{r.status}</td></tr>)}{!report.rows.length&&<tr><td colSpan="8" className="empty">{L.empty}</td></tr>}</tbody><tfoot><tr><th colSpan="4">الإجمالي</th><th>{Number(report.totals.netRevenue).toFixed(2)}</th><th></th><th>{Number(report.totals.commission).toFixed(2)}</th><th></th></tr></tfoot></table></div>;
}

export default function StablesModule({ companyId }) {
  const { i18n } = useTranslation(); const lang=i18n.language?.startsWith("ar")?"ar":"en"; const L={...text[lang],...extraText[lang]};
  const tabs=useMemo(()=>STABLE_TABS.map(x=>({...x,label:L[x.id]})),[L]); const [tab]=useModuleTab("/stables",tabs);
  const [data,setData]=useState({overview:null,stables:[],stalls:[],horses:[],contracts:[],care:[],services:[],trainers:[],lessonTypes:[],lessons:[],competitions:[],owners:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty[tab]||{});
  const load=useCallback(async()=>{if(!companyId)return;setLoading(true);setError("");try{const [overview,stables,stalls,horses,contracts,care,services,trainers,lessonTypes,lessons,competitions,owners]=await Promise.all([stableApi.overview(companyId),stableApi.listStables(companyId),stableApi.listStalls(companyId),stableApi.listHorses(companyId),stableApi.listContracts(companyId),stableApi.listCare(companyId),stableApi.listServices(companyId),stableApi.listTrainers(companyId),stableApi.listLessonTypes(companyId),stableApi.listLessons(companyId),stableApi.listCompetitions(companyId),stableApi.listBoardingOwners(companyId)]);setData({overview,stables,stalls,horses,contracts,care,services,trainers,lessonTypes,lessons,competitions,owners});}catch(e){setError(e.message)}finally{setLoading(false)}},[companyId]);
  useEffect(()=>{load()},[load]); useEffect(()=>{setEditing(null);setForm({...empty[tab]})},[tab]);
  if(!companyId)return <p className="empty">{L.required}</p>;
  const save=async()=>{try{const payload={...clean(form),companyId}; const singular={stables:"Stable",stalls:"Stall",horses:"Horse",contracts:"Contract",care:"Care",services:"Service",trainers:"Trainer",lessonTypes:"LessonType",lessons:"Lesson",competitions:"Competition"}[tab]; if(editing) await stableApi[`update${singular}`](editing,payload); else await stableApi[`create${singular}`](payload); setEditing(null);setForm({...empty[tab]});await load();}catch(e){setError(e.message)}};
  const remove=async(id)=>{if(!window.confirm(L.confirm))return;try{const singular={stables:"Stable",stalls:"Stall",horses:"Horse",contracts:"Contract",care:"Care",services:"Service",trainers:"Trainer",lessonTypes:"LessonType",lessons:"Lesson",competitions:"Competition"}[tab];await stableApi[`delete${singular}`](id);await load()}catch(e){setError(e.message)}};
  const printContract=async(r)=>{try{const {blob,filename}=await stableApi.downloadContract(r.id);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename||`livery-contract-${r.contractNumber||r.id}.pdf`;a.click();URL.revokeObjectURL(url)}catch(e){setError(e.message)}};
  const sendContract=async(r)=>{try{let email=r.ownerEmail;if(!email)email=window.prompt(L.email)||"";if(!email)return;await stableApi.sendContract(r.id,email);window.alert(L.sent);await load()}catch(e){setError(e.message)}};
  const invoiceLesson=async(r)=>{try{const invoice=await stableApi.createLessonInvoice(r.id);window.alert(`${L.invoiceCreated}: ${invoice.invoiceNumber}`);await load()}catch(e){setError(e.message)}};
  const edit=(r)=>{setEditing(r.id);setForm(Object.fromEntries(Object.keys(empty[tab]).map(k=>[k,k==="monthlyServices"?(r.monthlyServices||[]).map(x=>({serviceId:x.serviceId,trainerId:x.trainerId||"",quantity:Number(x.quantity),unitPrice:x.unitPrice??x.service?.price??""})):(k.endsWith("Date")||k==="performedAt"||k==="startDate"||k==="endDate")&&r[k]?new Date(r[k]).toISOString().slice(0,10):(r[k]??"")])))};
  const rows=data[tab]||[];
  return <div><div className="section-title"><Breadcrumb parts={[L.title]}/><h2>{L.title}</h2></div><SubTabs tabs={tabs} active={tab} basePath="/stables"/>{error&&<p className="balance-bad">{error}</p>}
    {tab==="overview"&&data.overview&&<><div className="kpi-grid"><div className="kpi-card"><strong>{data.overview.stables}</strong><span>{L.stables}</span></div><div className="kpi-card"><strong>{data.overview.horses}</strong><span>{L.activeHorses}</span></div><div className="kpi-card"><strong>{data.overview.availableStalls}</strong><span>{L.availableStalls}</span></div><div className="kpi-card"><strong>{data.overview.activeContracts}</strong><span>{L.activeContracts}</span></div></div><div className="panel"><h3>{L.upcoming}</h3>{data.overview.upcomingCare.map(x=><p key={x.id}>{x.horse.name} — {x.description} — {fmtDate(x.nextDueDate)}</p>)}{!data.overview.upcomingCare.length&&<p className="empty">{L.empty}</p>}</div></>}
    {tab==="billing"&&<BoardingBillingPanel companyId={companyId} owners={data.owners} trainers={data.trainers} L={L} onCreated={load}/>}
    {tab==="commissions"&&<CommissionReportPanel companyId={companyId} L={L}/>}
    {!["overview","billing","commissions"].includes(tab)&&<><div className="panel form-panel"><div className="form-grid"><Editor kind={tab} value={form} setValue={setForm} L={L} {...data}/></div><div className="form-btn-group">{editing&&<button className="btn-ghost" onClick={()=>{setEditing(null);setForm({...empty[tab]})}}>{L.cancel}</button>}<button className="btn-primary" onClick={save}>{editing?L.save:L.add}</button></div></div>{loading?<p className="empty">{L.loading}</p>:<div className="panel"><table className="ledger-table"><thead><tr><th>{tab==="stalls"?L.number:tab==="care"?L.description:L.name}</th><th>{L.stable}</th><th>{L.status}</th><th>{L.notes}</th><th>الإجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name||r.nameAr||r.studentName||r.number||r.description||r.horse?.name}</td><td>{r.stable?.name||r.horse?.name||"—"}</td><td>{r.status||r.type||r.category||r.level||"—"}</td><td>{r.salesInvoice?.invoiceNumber||r.notes||r.specialties||r.nameEn||"—"}</td><td className="row-actions">{tab==="lessons"&&!r.salesInvoiceId&&!["cancelled","no_show"].includes(r.status)&&<button className="btn-primary" onClick={()=>invoiceLesson(r)}><NavIcon name="billing"/> {L.lessonInvoice}</button>}{tab==="contracts"&&<><button className="btn-ghost" title={L.print} onClick={()=>printContract(r)}><NavIcon name="print"/> {L.print}</button><button className="btn-ghost" title={L.send} onClick={()=>sendContract(r)}><NavIcon name="send"/> {L.send}</button></>}<button className="btn-ghost" title={L.edit} onClick={()=>edit(r)}><NavIcon name="edit"/> {L.edit}</button><button className="btn-ghost danger" title={L.del} onClick={()=>remove(r.id)}><NavIcon name="delete"/> {L.del}</button></td></tr>)}{!rows.length&&<tr><td colSpan="5" className="empty">{L.empty}</td></tr>}</tbody></table></div>}</>}
  </div>;
}
