import { renderHtmlToPdf } from "./zatca/pdf/renderPdf";
import type { getAccountLedger } from "../modules/reports/reports.service";

type Ledger = Awaited<ReturnType<typeof getAccountLedger>>;
const escape = (value: unknown) => String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const money = (value: number) => value.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
export function buildAccountLedgerHtml(ledger: Ledger, company: {name:string;vatNumber:string|null}|null, filters: {from?:string;to?:string;lang:string}) {
  const en = filters.lang === "en";
  const labels = en ? ["Detailed Account Ledger","Account","Account code","Period","VAT number","Opening balance","Total debit","Total credit","Closing balance","Date","Entry #","Memo","Debit","Credit","Balance","Prepared by","Reviewed by","Official stamp"] : ["كشف حساب تفصيلي","اسم الحساب","رقم الحساب","الفترة الزمنية","الرقم الضريبي","رصيد افتتاحي","إجمالي مدين","إجمالي دائن","رصيد ختامي","التاريخ","رقم القيد","البيان","مدين","دائن","الرصيد","إعداد","مراجعة","ختم رسمي"];
  const side = (ledger.closingBalance >= 0) === (ledger.normalSide === "debit") ? labels[12] : labels[13];
  const debit = ledger.rows.reduce((sum,r)=>sum+r.debit,0), credit = ledger.rows.reduce((sum,r)=>sum+r.credit,0);
  const group = !ledger.account.isPosting;
  const period = `${filters.from || (en ? "Start of activity" : "بداية النشاط")} — ${filters.to || (en ? "Today" : "اليوم")}`;
  const rows = ledger.rows.map(r=>`<tr><td>${escape(r.date.toISOString().slice(0,10))}</td><td>${escape(r.entryNumber || r.journalEntryId.slice(-8))}</td><td>${escape(r.entryMemo)}<small>${escape(r.lineDescription)}</small></td>${group ? `<td>${escape(r.accountCode)} — ${escape(r.accountName)}</td>` : ""}<td class="num debit">${r.debit ? money(r.debit) : "—"}</td><td class="num credit">${r.credit ? money(r.credit) : "—"}</td><td class="num">${money(r.balance)}</td></tr>`).join("");
  return `<!doctype html><html lang="${en ? "en" : "ar"}" dir="${en ? "ltr" : "rtl"}"><head><meta charset="UTF-8"><style>
  body{font-family:Arial,'Noto Sans Arabic',sans-serif;color:#1f2937;font-size:10px;margin:0}header{background:#20252d;color:white;padding:22px;display:flex;justify-content:space-between;align-items:center}h1{font-size:20px;margin:0}h2{font-size:17px;color:#f59e0b;margin:0}.grid{display:flex;gap:8px;padding:16px 0}.box{flex:1;min-width:0;padding:12px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:9px}.box span{display:block;color:#64748b;margin-bottom:8px}.box strong{font-size:13px}.summary .box:last-child{background:#20252d;color:#f59e0b}.summary .box:last-child span{color:white}table{width:100%;border-collapse:collapse}th{background:#f8fafc;text-align:start;color:#64748b}td,th{padding:9px 5px;border-bottom:1px solid #e2e8f0}small{display:block;color:#64748b;margin-top:4px}.num{white-space:nowrap;direction:ltr;text-align:end}.debit{color:#15803d}.credit{color:#dc2626}tbody tr:nth-child(even){background:#fafbfc}tfoot td{background:#20252d;color:#fbbf24;font-weight:bold}tfoot{display:table-row-group;break-inside:avoid}thead{display:table-header-group}tr,.grid,footer{break-inside:avoid}.signature-row td{background:white;color:#1f2937}footer{display:flex;justify-content:space-around;padding:16px 0;text-align:center}footer div{width:26%;height:40px;border-bottom:1px solid #cbd5e1}
  </style></head><body><header><div><h1>${escape(company?.name || "أثر المحاسبي")}</h1><p>أثر المحاسبي</p></div><div><h2>${labels[0]}</h2><p>Account Ledger</p></div></header>
  <section class="grid">${[[labels[1],en && ledger.account.nameEn ? ledger.account.nameEn : ledger.account.name],[labels[2],ledger.account.code],[labels[3],period],[labels[4],company?.vatNumber || "—"]].map(([l,v])=>`<div class="box"><span>${l}</span><strong>${escape(v)}</strong></div>`).join("")}</section>
  <section class="grid summary">${[[labels[5],money(ledger.openingBalance)],[labels[6],money(debit)],[labels[7],money(credit)],[`${labels[8]} (${side})`,money(Math.abs(ledger.closingBalance))]].map(([l,v])=>`<div class="box"><span>${l}</span><strong>${v}</strong></div>`).join("")}</section>
  <table><thead><tr>${[labels[9],labels[10],labels[11],...(group ? [labels[1]] : []),labels[12],labels[13],labels[14]].map(l=>`<th>${l}</th>`).join("")}</tr></thead><tbody><tr><td colspan="${group?6:5}">${labels[5]}</td><td class="num">${money(ledger.openingBalance)}</td></tr>${rows}</tbody><tfoot><tr><td colspan="${group?4:3}">${labels[8]} (${side})</td><td class="num">${money(debit)}</td><td class="num">${money(credit)}</td><td class="num">${money(ledger.closingBalance)}</td></tr><tr class="signature-row"><td colspan="${group?7:6}"><footer><div>${labels[15]}</div><div>${labels[16]}</div><div>${labels[17]}</div></footer></td></tr></tfoot></table></body></html>`;
}
export async function buildAccountLedgerPdf(...args: Parameters<typeof buildAccountLedgerHtml>) { return renderHtmlToPdf(buildAccountLedgerHtml(...args)); }
