import { requirePositionAction } from "../../middleware/positionMatrix";
import { Router } from "express";
import { authenticate, requireRole, blockMutationsWhenReadOnly } from "../../middleware/auth";
import { validateBody } from "../../middleware/validate";
import * as c from "./stables.controller";
import * as s from "./stables.schemas";

export const stableRoutes = Router();
stableRoutes.use(authenticate, blockMutationsWhenReadOnly);
const edit = requireRole("admin", "finance_manager");
stableRoutes.get("/overview", requirePositionAction("stables", "read"), c.overview);
stableRoutes.get("/boarding-billing/owners", requirePositionAction("stables", "read"), c.listBoardingOwners);
stableRoutes.post("/boarding-billing/invoices", requirePositionAction("stables", "create"), requirePositionAction("salesInvoices", "create"), edit, validateBody(s.createBoardingInvoiceSchema), c.createBoardingInvoice);
stableRoutes.get("/trainer-commissions/report", requirePositionAction("stables", "read"), c.trainerCommissionReport);
stableRoutes.get("/", requirePositionAction("stables", "read"), c.listStables); stableRoutes.post("/", requirePositionAction("stables", "create"), edit, validateBody(s.createStableSchema), c.createStable);
stableRoutes.patch("/:id", requirePositionAction("stables", "edit"), edit, validateBody(s.updateStableSchema), c.updateStable); stableRoutes.delete("/:id", requirePositionAction("stables", "delete"), edit, c.deleteStable);
stableRoutes.get("/stalls/list", requirePositionAction("stables", "read"), c.listStalls); stableRoutes.post("/stalls", requirePositionAction("stables", "create"), edit, validateBody(s.createStallSchema), c.createStall);
stableRoutes.patch("/stalls/:id", requirePositionAction("stables", "edit"), edit, validateBody(s.updateStallSchema), c.updateStall); stableRoutes.delete("/stalls/:id", requirePositionAction("stables", "delete"), edit, c.deleteStall);
stableRoutes.get("/horses/list", requirePositionAction("stables", "read"), c.listHorses); stableRoutes.post("/horses", requirePositionAction("stables", "create"), edit, validateBody(s.createHorseSchema), c.createHorse);
stableRoutes.patch("/horses/:id", requirePositionAction("stables", "edit"), edit, validateBody(s.updateHorseSchema), c.updateHorse); stableRoutes.delete("/horses/:id", requirePositionAction("stables", "delete"), edit, c.deleteHorse);
stableRoutes.get("/contracts/list", requirePositionAction("stables", "read"), c.listContracts); stableRoutes.post("/contracts", requirePositionAction("stables", "create"), edit, validateBody(s.createContractSchema), c.createContract);
stableRoutes.get("/contracts/:id/pdf", requirePositionAction("stables", "read"), c.downloadContractPdf); stableRoutes.post("/contracts/:id/send-email", requirePositionAction("stables", "edit"), edit, validateBody(s.sendContractEmailSchema), c.emailContract);
stableRoutes.patch("/contracts/:id", requirePositionAction("stables", "edit"), edit, validateBody(s.updateContractSchema), c.updateContract); stableRoutes.delete("/contracts/:id", requirePositionAction("stables", "delete"), edit, c.deleteContract);
stableRoutes.get("/care/list", requirePositionAction("stables", "read"), c.listCare); stableRoutes.post("/care", requirePositionAction("stables", "create"), edit, validateBody(s.createCareRecordSchema), c.createCare);
stableRoutes.patch("/care/:id", requirePositionAction("stables", "edit"), edit, validateBody(s.updateCareRecordSchema), c.updateCare); stableRoutes.delete("/care/:id", requirePositionAction("stables", "delete"), edit, c.deleteCare);
stableRoutes.get("/trainers/list", requirePositionAction("stables", "read"),c.listTrainers); stableRoutes.post("/trainers", requirePositionAction("stables", "create"),edit,validateBody(s.trainerSchema),c.createTrainer); stableRoutes.patch("/trainers/:id", requirePositionAction("stables", "edit"),edit,validateBody(s.updateTrainerSchema),c.updateTrainer); stableRoutes.delete("/trainers/:id", requirePositionAction("stables", "delete"),edit,c.deleteTrainer);
stableRoutes.get("/lesson-types/list", requirePositionAction("stables", "read"),c.listLessonTypes); stableRoutes.post("/lesson-types", requirePositionAction("stables", "create"),edit,validateBody(s.lessonTypeSchema),c.createLessonType); stableRoutes.patch("/lesson-types/:id", requirePositionAction("stables", "edit"),edit,validateBody(s.updateLessonTypeSchema),c.updateLessonType); stableRoutes.delete("/lesson-types/:id", requirePositionAction("stables", "delete"),edit,c.deleteLessonType);
stableRoutes.get("/lessons/list", requirePositionAction("stables", "read"),c.listLessons); stableRoutes.post("/lessons", requirePositionAction("stables", "create"),edit,validateBody(s.lessonSchema),c.createLesson); stableRoutes.patch("/lessons/:id", requirePositionAction("stables", "edit"),edit,validateBody(s.updateLessonSchema),c.updateLesson); stableRoutes.delete("/lessons/:id", requirePositionAction("stables", "delete"),edit,c.deleteLesson);
stableRoutes.post("/lessons/:id/invoice", requirePositionAction("stables", "create"), requirePositionAction("salesInvoices", "create"),edit,c.createLessonInvoice);
stableRoutes.get("/competitions/list", requirePositionAction("stables", "read"),c.listCompetitions); stableRoutes.post("/competitions", requirePositionAction("stables", "create"),edit,validateBody(s.competitionSchema),c.createCompetition); stableRoutes.patch("/competitions/:id", requirePositionAction("stables", "edit"),edit,validateBody(s.updateCompetitionSchema),c.updateCompetition); stableRoutes.delete("/competitions/:id", requirePositionAction("stables", "delete"),edit,c.deleteCompetition);
stableRoutes.get("/care-services/list", requirePositionAction("stables", "read"),c.listCareServices); stableRoutes.post("/care-services", requirePositionAction("stables", "create"),edit,validateBody(s.careServiceSchema),c.createCareService); stableRoutes.patch("/care-services/:id", requirePositionAction("stables", "edit"),edit,validateBody(s.updateCareServiceSchema),c.updateCareService); stableRoutes.delete("/care-services/:id", requirePositionAction("stables", "delete"),edit,c.deleteCareService);
