import { Router } from "express";
import { authenticate, requireRole } from "../../middleware/auth";
import { validateBody } from "../../middleware/validate";
import * as c from "./stables.controller";
import * as s from "./stables.schemas";

export const stableRoutes = Router();
stableRoutes.use(authenticate);
const edit = requireRole("admin", "finance_manager");
stableRoutes.get("/overview", c.overview);
stableRoutes.get("/boarding-billing/owners", c.listBoardingOwners);
stableRoutes.post("/boarding-billing/invoices", edit, validateBody(s.createBoardingInvoiceSchema), c.createBoardingInvoice);
stableRoutes.get("/trainer-commissions/report", c.trainerCommissionReport);
stableRoutes.get("/", c.listStables); stableRoutes.post("/", edit, validateBody(s.createStableSchema), c.createStable);
stableRoutes.patch("/:id", edit, validateBody(s.updateStableSchema), c.updateStable); stableRoutes.delete("/:id", edit, c.deleteStable);
stableRoutes.get("/stalls/list", c.listStalls); stableRoutes.post("/stalls", edit, validateBody(s.createStallSchema), c.createStall);
stableRoutes.patch("/stalls/:id", edit, validateBody(s.updateStallSchema), c.updateStall); stableRoutes.delete("/stalls/:id", edit, c.deleteStall);
stableRoutes.get("/horses/list", c.listHorses); stableRoutes.post("/horses", edit, validateBody(s.createHorseSchema), c.createHorse);
stableRoutes.patch("/horses/:id", edit, validateBody(s.updateHorseSchema), c.updateHorse); stableRoutes.delete("/horses/:id", edit, c.deleteHorse);
stableRoutes.get("/contracts/list", c.listContracts); stableRoutes.post("/contracts", edit, validateBody(s.createContractSchema), c.createContract);
stableRoutes.get("/contracts/:id/pdf", c.downloadContractPdf); stableRoutes.post("/contracts/:id/send-email", edit, validateBody(s.sendContractEmailSchema), c.emailContract);
stableRoutes.patch("/contracts/:id", edit, validateBody(s.updateContractSchema), c.updateContract); stableRoutes.delete("/contracts/:id", edit, c.deleteContract);
stableRoutes.get("/care/list", c.listCare); stableRoutes.post("/care", edit, validateBody(s.createCareRecordSchema), c.createCare);
stableRoutes.patch("/care/:id", edit, validateBody(s.updateCareRecordSchema), c.updateCare); stableRoutes.delete("/care/:id", edit, c.deleteCare);
stableRoutes.get("/trainers/list",c.listTrainers); stableRoutes.post("/trainers",edit,validateBody(s.trainerSchema),c.createTrainer); stableRoutes.patch("/trainers/:id",edit,validateBody(s.updateTrainerSchema),c.updateTrainer); stableRoutes.delete("/trainers/:id",edit,c.deleteTrainer);
stableRoutes.get("/lesson-types/list",c.listLessonTypes); stableRoutes.post("/lesson-types",edit,validateBody(s.lessonTypeSchema),c.createLessonType); stableRoutes.patch("/lesson-types/:id",edit,validateBody(s.updateLessonTypeSchema),c.updateLessonType); stableRoutes.delete("/lesson-types/:id",edit,c.deleteLessonType);
stableRoutes.get("/lessons/list",c.listLessons); stableRoutes.post("/lessons",edit,validateBody(s.lessonSchema),c.createLesson); stableRoutes.patch("/lessons/:id",edit,validateBody(s.updateLessonSchema),c.updateLesson); stableRoutes.delete("/lessons/:id",edit,c.deleteLesson);
stableRoutes.post("/lessons/:id/invoice",edit,c.createLessonInvoice);
stableRoutes.get("/competitions/list",c.listCompetitions); stableRoutes.post("/competitions",edit,validateBody(s.competitionSchema),c.createCompetition); stableRoutes.patch("/competitions/:id",edit,validateBody(s.updateCompetitionSchema),c.updateCompetition); stableRoutes.delete("/competitions/:id",edit,c.deleteCompetition);
stableRoutes.get("/care-services/list",c.listCareServices); stableRoutes.post("/care-services",edit,validateBody(s.careServiceSchema),c.createCareService); stableRoutes.patch("/care-services/:id",edit,validateBody(s.updateCareServiceSchema),c.updateCareService); stableRoutes.delete("/care-services/:id",edit,c.deleteCareService);
