import React, { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell } from "recharts";
import { getComprehensiveMonthly, updateComprehensiveSettings } from "../api/reports";
import { fmt } from "../legacy/constants";
import { CHART_PALETTE, CHART_GRID, chartTooltipStyle, colorAt } from "./dashboard/chartTheme";

const currentMonth = () => new Date().toISOString().slice(0, 7);
const ChartBox = ({ title, children }) => <div className="panel chart-panel"><h3>{title}</h3>{children}</div>;
const Aging = ({ data, t }) => <table className="ledger-table"><thead><tr><th>{t("reports.monthly.agingUnder30")}</th><th>{t("reports.monthly.aging30to60")}</th><th>{t("reports.monthly.aging60to90")}</th><th>{t("reports.monthly.agingOver90")}</th></tr></thead><tbody><tr>{["under30","d30to60","d60to90","over90"].map(k=><td className="num" key={k}>{fmt(data[k])}</td>)}</tr></tbody></table>;

export default function ComprehensiveMonthlyReport({ companyId }) {
  const { t } = useTranslation();
  const currency = t("common.currency");
  const [month,setMonth]=useState(currentMonth()); const [data,setData]=useState(null); const [notes,setNotes]=useState(""); const [error,setError]=useState(""); const [editing,setEditing]=useState(false); const [settings,setSettings]=useState(null);
  useEffect(()=>{ setError(""); getComprehensiveMonthly({companyId,month}).then(r=>{setData(r);setSettings(r.settings);setNotes(r.generatedNotes.join("\n"));}).catch(e=>setError(e.message)); },[companyId,month]);
  if(error) return <p className="balance-bad">{error}</p>; if(!data) return <p className="empty">{t("reports.monthly.preparing")}</p>;
  const significant=(r)=>r.changePct!=null&&Math.abs(r.changePct)>=data.settings.expenseIncreasePct;
  const saveSettings=async()=>{ await updateComprehensiveSettings(companyId,settings); setEditing(false); const fresh=await getComprehensiveMonthly({companyId,month}); setData(fresh); };
  return <div className="monthly-report">
    <div className="filter-bar no-print"><label>{t("reports.monthly.monthLabel")}<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="btn-primary" onClick={()=>window.print()}>{t("reports.monthly.exportBtn")}</button>{companyId&&<button className="btn-secondary" onClick={()=>setEditing(!editing)}>{t("reports.monthly.alertThresholdsBtn")}</button>}</div>
    {editing&&<div className="panel no-print"><h3>{t("reports.monthly.alertThresholdsTitle")}</h3><div className="filter-bar"><label>{t("reports.monthly.expenseIncreasePctLabel")}<input type="number" value={settings.expenseIncreasePct} onChange={e=>setSettings({...settings,expenseIncreasePct:e.target.value})}/></label><label>{t("reports.monthly.minimumCashLabel")}<input type="number" value={settings.minimumCash} onChange={e=>setSettings({...settings,minimumCash:e.target.value})}/></label><label>{t("reports.monthly.maximumReceivablesLabel")}<input type="number" value={settings.maximumReceivables} onChange={e=>setSettings({...settings,maximumReceivables:e.target.value})}/></label><button className="btn-primary" onClick={saveSettings}>{t("common.save")}</button></div></div>}
    <h2>{t("reports.monthly.titleWithMonth", { month, scope: data.scope==="group"?t("reports.monthly.scopeGroup"):"" })}</h2>
    <section><h3>{t("reports.monthly.sectionA")}</h3><table className="ledger-table"><tbody><tr><td>{t("reports.income.totalRevenue")}</td><td className="num">{fmt(data.revenue)}</td></tr>{data.expenseSummary.map(x=><tr key={x.category}><td>{x.category}</td><td className="num">{fmt(x.value)}</td></tr>)}<tr><td className="strong">{t("reports.income.totalExpenses")}</td><td className="num strong">{fmt(data.expense)}</td></tr></tbody></table><ChartBox title={t("reports.monthly.chartRevenueExpense")}><ResponsiveContainer width="100%" height={220}><BarChart data={[{name:t("reports.monthly.revenueLabel"),value:data.revenue},{name:t("reports.monthly.expenseLabel"),value:data.expense}]}><CartesianGrid stroke={CHART_GRID}/><XAxis dataKey="name"/><YAxis/><Tooltip {...chartTooltipStyle}/><Bar dataKey="value" fill={CHART_PALETTE[0]}/></BarChart></ResponsiveContainer></ChartBox></section>
    <section><h3>{t("reports.monthly.sectionB")}</h3><div className={`panel net-row ${data.netProfitChangePct>=0?"balance-ok":"balance-bad"}`}><div style={{fontSize:30,fontWeight:800}}>{fmt(data.netProfit)} {currency}</div><div>{data.netProfitChangePct==null?t("reports.monthly.noComparison"):t("reports.monthly.vsLastMonth",{pct:data.netProfitChangePct})}</div></div></section>
    <section><h3>{t("reports.monthly.sectionC")}</h3><table className="ledger-table"><tbody><tr><td>{t("reports.monthly.payrollPaid")}</td><td className="num">{fmt(data.payroll.paid)}</td></tr><tr><td>{t("reports.monthly.payrollUnpaid")}</td><td className="num">{fmt(data.payroll.unpaid)}</td></tr><tr><td>{t("reports.monthly.eosAccrual")}</td><td className="num">{fmt(data.payroll.endOfService)}</td></tr></tbody></table></section>
    <section><h3>{t("reports.monthly.sectionD")}</h3><ChartBox title={t("reports.monthly.topExpenseItems")}><ResponsiveContainer width="100%" height={280}><BarChart data={data.expenseDetails} layout="vertical"><XAxis type="number"/><YAxis type="category" dataKey="name" width={150}/><Tooltip {...chartTooltipStyle}/><Bar dataKey="value" fill={CHART_PALETTE[1]}/></BarChart></ResponsiveContainer></ChartBox></section>
    <section><h3>{t("reports.monthly.sectionE")}</h3><ChartBox title={t("reports.monthly.receiptsVsPayments")}><ResponsiveContainer width="100%" height={220}><BarChart data={[data.cashFlow]}><XAxis dataKey="net"/><YAxis/><Tooltip {...chartTooltipStyle}/><Legend/><Bar dataKey="receipts" name={t("reports.monthly.receipts")} fill="#2F5D5A"/><Bar dataKey="payments" name={t("reports.monthly.payments")} fill="#A8432B"/></BarChart></ResponsiveContainer></ChartBox><p className="strong">{t("reports.monthly.netFlow", { amount: fmt(data.cashFlow.net) })}</p></section>
    <section><h3>{t("reports.monthly.sectionF")}</h3><table className="ledger-table"><tbody>{data.cashAccounts.map(x=><tr key={x.accountId}><td>{x.name}</td><td className="num">{fmt(x.balance)}</td></tr>)}<tr><td className="strong">{t("reports.monthly.total")}</td><td className="num strong">{fmt(data.totalCash)}</td></tr></tbody></table><ChartBox title={t("reports.monthly.cashDistribution")}><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={data.cashAccounts} dataKey="balance" nameKey="name" innerRadius={50} outerRadius={85}>{data.cashAccounts.map((_,i)=><Cell key={i} fill={colorAt(i)}/>)}</Pie><Tooltip {...chartTooltipStyle}/><Legend/></PieChart></ResponsiveContainer></ChartBox></section>
    <section><h3>{t("reports.monthly.sectionG")}</h3><p>{t("reports.monthly.receivablesLabel")}: <b>{fmt(data.receivables.total)}</b> — {t("reports.monthly.payablesLabel")}: <b>{fmt(data.payables.total)}</b></p><h4>{t("reports.monthly.receivablesAgingTitle")}</h4><Aging data={data.receivables.aging} t={t}/><h4>{t("reports.monthly.payablesAgingTitle")}</h4><Aging data={data.payables.aging} t={t}/></section>
    <section><h3>{t("reports.monthly.sectionH")}</h3><table className="ledger-table"><tbody>{data.liabilities.map((x,i)=><tr key={i}><td>{x.name}</td><td className="num">{fmt(x.amount)}</td></tr>)}{!data.liabilities.length&&<tr><td className="empty">{t("reports.monthly.noLiabilities")}</td></tr>}</tbody></table><p className="empty">{t("reports.monthly.liabilitiesNote")}</p></section>
    <section><h3>{t("reports.monthly.sectionI")}</h3><table className="ledger-table"><thead><tr><th>{t("reports.monthly.table.item")}</th><th>{t("reports.monthly.table.current")}</th><th>{t("reports.monthly.table.previous")}</th><th>{t("reports.monthly.table.difference")}</th><th>{t("reports.monthly.table.percentage")}</th></tr></thead><tbody>{data.comparison.map(r=><tr className={significant(r)?(r.difference>0?"balance-bad":"balance-ok"):""} key={r.label}><td>{r.label}</td><td className="num">{fmt(r.current)}</td><td className="num">{fmt(r.previous)}</td><td className="num">{fmt(r.difference)}</td><td>{r.changePct==null?"—":`${r.changePct}%`}</td></tr>)}</tbody></table></section>
    <section><h3>{t("reports.monthly.sectionJ")}</h3><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={8} style={{width:"100%",padding:12}} aria-label={t("reports.monthly.notesAriaLabel")}/><p className="empty">{t("reports.monthly.notesNote")}</p></section>
  </div>;
}
