import React, { useEffect, useState } from "react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell } from "recharts";
import { getComprehensiveMonthly, updateComprehensiveSettings } from "../api/reports";
import { fmt } from "../legacy/constants";
import { CHART_PALETTE, CHART_GRID, chartTooltipStyle, colorAt } from "./dashboard/chartTheme";

const currentMonth = () => new Date().toISOString().slice(0, 7);
const ChartBox = ({ title, children }) => <div className="panel chart-panel"><h3>{title}</h3>{children}</div>;
const Aging = ({ data }) => <table className="ledger-table"><thead><tr><th>أقل من 30</th><th>30–60</th><th>60–90</th><th>أكثر من 90</th></tr></thead><tbody><tr>{["under30","d30to60","d60to90","over90"].map(k=><td className="num" key={k}>{fmt(data[k])}</td>)}</tr></tbody></table>;

export default function ComprehensiveMonthlyReport({ companyId }) {
  const [month,setMonth]=useState(currentMonth()); const [data,setData]=useState(null); const [notes,setNotes]=useState(""); const [error,setError]=useState(""); const [editing,setEditing]=useState(false); const [settings,setSettings]=useState(null);
  useEffect(()=>{ setError(""); getComprehensiveMonthly({companyId,month}).then(r=>{setData(r);setSettings(r.settings);setNotes(r.generatedNotes.join("\n"));}).catch(e=>setError(e.message)); },[companyId,month]);
  if(error) return <p className="balance-bad">{error}</p>; if(!data) return <p className="empty">جارٍ إعداد التقرير...</p>;
  const significant=(r)=>r.changePct!=null&&Math.abs(r.changePct)>=data.settings.expenseIncreasePct;
  const saveSettings=async()=>{ await updateComprehensiveSettings(companyId,settings); setEditing(false); const fresh=await getComprehensiveMonthly({companyId,month}); setData(fresh); };
  return <div className="monthly-report">
    <div className="filter-bar no-print"><label>الشهر<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="btn-primary" onClick={()=>window.print()}>تصدير PDF / طباعة</button>{companyId&&<button className="btn-secondary" onClick={()=>setEditing(!editing)}>حدود التنبيه</button>}</div>
    {editing&&<div className="panel no-print"><h3>حدود التنبيه</h3><div className="filter-bar"><label>زيادة المصروف ٪<input type="number" value={settings.expenseIncreasePct} onChange={e=>setSettings({...settings,expenseIncreasePct:e.target.value})}/></label><label>أدنى نقدية<input type="number" value={settings.minimumCash} onChange={e=>setSettings({...settings,minimumCash:e.target.value})}/></label><label>أقصى ذمم مدينة<input type="number" value={settings.maximumReceivables} onChange={e=>setSettings({...settings,maximumReceivables:e.target.value})}/></label><button className="btn-primary" onClick={saveSettings}>حفظ</button></div></div>}
    <h2>التقرير المالي الشهري الشامل — {month} {data.scope==="group"?"(المجموعة كاملة)":""}</h2>
    <section><h3>أ. ملخص الإيرادات والمصروفات</h3><table className="ledger-table"><tbody><tr><td>إجمالي الإيرادات</td><td className="num">{fmt(data.revenue)}</td></tr>{data.expenseSummary.map(x=><tr key={x.category}><td>{x.category}</td><td className="num">{fmt(x.value)}</td></tr>)}<tr><td className="strong">إجمالي المصروفات</td><td className="num strong">{fmt(data.expense)}</td></tr></tbody></table><ChartBox title="الإيرادات والمصروفات"><ResponsiveContainer width="100%" height={220}><BarChart data={[{name:"الإيرادات",value:data.revenue},{name:"المصروفات",value:data.expense}]}><CartesianGrid stroke={CHART_GRID}/><XAxis dataKey="name"/><YAxis/><Tooltip {...chartTooltipStyle}/><Bar dataKey="value" fill={CHART_PALETTE[0]}/></BarChart></ResponsiveContainer></ChartBox></section>
    <section><h3>ب. صافي الربح أو الخسارة</h3><div className={`panel net-row ${data.netProfitChangePct>=0?"balance-ok":"balance-bad"}`}><div style={{fontSize:30,fontWeight:800}}>{fmt(data.netProfit)} ر.س</div><div>{data.netProfitChangePct==null?"لا تتوفر مقارنة":`${data.netProfitChangePct}% عن الشهر السابق`}</div></div></section>
    <section><h3>ج. الرواتب والأجور والمستحقات</h3><table className="ledger-table"><tbody><tr><td>رواتب مصروفة</td><td className="num">{fmt(data.payroll.paid)}</td></tr><tr><td>رواتب مستحقة غير مدفوعة</td><td className="num">{fmt(data.payroll.unpaid)}</td></tr><tr><td>مخصص نهاية الخدمة</td><td className="num">{fmt(data.payroll.endOfService)}</td></tr></tbody></table></section>
    <section><h3>د. المصروفات التشغيلية والإدارية</h3><ChartBox title="أبرز بنود المصروف"><ResponsiveContainer width="100%" height={280}><BarChart data={data.expenseDetails} layout="vertical"><XAxis type="number"/><YAxis type="category" dataKey="name" width={150}/><Tooltip {...chartTooltipStyle}/><Bar dataKey="value" fill={CHART_PALETTE[1]}/></BarChart></ResponsiveContainer></ChartBox></section>
    <section><h3>هـ. التدفقات النقدية</h3><ChartBox title="المقبوضات مقابل المدفوعات"><ResponsiveContainer width="100%" height={220}><BarChart data={[data.cashFlow]}><XAxis dataKey="net"/><YAxis/><Tooltip {...chartTooltipStyle}/><Legend/><Bar dataKey="receipts" name="المقبوضات" fill="#2F5D5A"/><Bar dataKey="payments" name="المدفوعات" fill="#A8432B"/></BarChart></ResponsiveContainer></ChartBox><p className="strong">صافي التدفق: {fmt(data.cashFlow.net)} ر.س</p></section>
    <section><h3>و. أرصدة البنوك والصندوق</h3><table className="ledger-table"><tbody>{data.cashAccounts.map(x=><tr key={x.accountId}><td>{x.name}</td><td className="num">{fmt(x.balance)}</td></tr>)}<tr><td className="strong">الإجمالي</td><td className="num strong">{fmt(data.totalCash)}</td></tr></tbody></table><ChartBox title="توزيع النقدية"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={data.cashAccounts} dataKey="balance" nameKey="name" innerRadius={50} outerRadius={85}>{data.cashAccounts.map((_,i)=><Cell key={i} fill={colorAt(i)}/>)}</Pie><Tooltip {...chartTooltipStyle}/><Legend/></PieChart></ResponsiveContainer></ChartBox></section>
    <section><h3>ز. الذمم المدينة والذمم الدائنة</h3><p>المدينة: <b>{fmt(data.receivables.total)}</b> — الدائنة: <b>{fmt(data.payables.total)}</b></p><h4>تعمير الذمم المدينة</h4><Aging data={data.receivables.aging}/><h4>تعمير الذمم الدائنة</h4><Aging data={data.payables.aging}/></section>
    <section><h3>ح. الالتزامات المالية المستحقة</h3><table className="ledger-table"><tbody>{data.liabilities.map((x,i)=><tr key={i}><td>{x.name}</td><td className="num">{fmt(x.amount)}</td></tr>)}{!data.liabilities.length&&<tr><td className="empty">لا توجد التزامات مصنفة.</td></tr>}</tbody></table><p className="empty">تعرض الأرصدة الحالية؛ تاريخ الاستحقاق غير متاح للحسابات القديمة.</p></section>
    <section><h3>ط. مقارنة الشهر الحالي بالشهر السابق</h3><table className="ledger-table"><thead><tr><th>البند</th><th>الحالي</th><th>السابق</th><th>الفرق</th><th>النسبة</th></tr></thead><tbody>{data.comparison.map(r=><tr className={significant(r)?(r.difference>0?"balance-bad":"balance-ok"):""} key={r.label}><td>{r.label}</td><td className="num">{fmt(r.current)}</td><td className="num">{fmt(r.previous)}</td><td className="num">{fmt(r.difference)}</td><td>{r.changePct==null?"—":`${r.changePct}%`}</td></tr>)}</tbody></table></section>
    <section><h3>ي. أبرز الملاحظات والتوصيات المالية</h3><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={8} style={{width:"100%",padding:12}} aria-label="الملاحظات والتوصيات"/><p className="empty">الملاحظات المقترحة مسودة قابلة للتعديل وتظهر بصيغتها الحالية في الطباعة.</p></section>
  </div>;
}
